-- create USER and set password
CREATE USER IF NOT EXISTS sm PASSWORD 'password';

CREATE TABLE IF NOT EXISTS genre
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);

CREATE TABLE IF NOT EXISTS age_rating
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);

CREATE TABLE IF NOT EXISTS film
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    age_rating_id BIGINT REFERENCES age_rating (id),
    name          TEXT NOT NULL,
    release_date  DATE,
    duration      SMALLINT,
    description   TEXT
);

CREATE TABLE IF NOT EXISTS film_genre
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id  BIGINT REFERENCES film (id),
    genre_id BIGINT REFERENCES genre (id),
    UNIQUE (film_id, genre_id)
);


CREATE TABLE IF NOT EXISTS app_user
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login     TEXT NOT NULL,
    name      TEXT,
    email     TEXT UNIQUE,
    birthdate DATE
);

CREATE TABLE IF NOT EXISTS film_user_like
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id BIGINT REFERENCES film (id),
    user_id BIGINT REFERENCES app_user (id),
    UNIQUE (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS user_friendship
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id_one BIGINT REFERENCES app_user (id),
    user_id_two BIGINT REFERENCES app_user (id),
    is_approved BOOLEAN default false,
    UNIQUE (user_id_one, user_id_two)
);